project:
  type: book

book:
  title: "Weekly Study diary"
  author: "Chuhui Tian"
  date: "2025/2/17"
  chapters:
    - index.qmd
    - week-1-diary.qmd
    - week-2-diary.qmd
    - week-3-diary.qmd
    - week-4-diary.qmd
    - week-5-diary.qmd
    - week-6-diary.qmd
    - week-7-diary.qmd
    - week-8-diary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    number-sections: true
    theme: cosmo

editor: visual






