---
title: "Introduction"
author: "Chuhui Tian"
date: "2025/2/17"
---
# Personal Introduction and Learning Objectives

Hello, I am Chuhui Tian, a student dedicated to the study and research of remote sensing and Geographic Information Systems (GIS). In this learning diary, I document my weekly learning experiences, practical experiments, and insights from literature reviews, aiming to build a comprehensive understanding of remote sensing analysis.

## My Background

I have a background in UCL studying in Urban Spacial Sicence and am passionate about data analysis and spatial information technology. Remote sensing is an essential tool for environmental monitoring, urban planning, and resource management, offering precise data to support informed decision-making.

## Learning Objectives

- **Theoretical Mastery:** Develop a systematic understanding of key concepts such as image processing, classification, and change detection.
- **Practical Skills:** Enhance my ability to process and analyze remote sensing data through hands-on experiments and case studies.
- **Literature Engagement:** Read and critically evaluate relevant literature to form a deep and unique perspective on remote sensing applications.
- **Knowledge Sharing:** Utilize the Quarto platform to create a dynamic, interactive learning diary that facilitates knowledge sharing and academic exchange.

I hope this diary not only consolidates my knowledge but also serves as many resource for peers and others interested in remote sensing technology. Let's learn and grow together!

---
